version: '3'
services:
  database:
    image: postgres
    ports:
      - 5402:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=transactions_db
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    networks:
      mynetwork:
        ipv4_address: 172.18.0.10

    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - 5000:5000
      volumes:
        - ./backend:/app
      networks:
      mynetwork:
        ipv4_address: 172.18.0.20

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1